const fs = require('fs');

const googleReviews = [
  { nameEn: "Aarti Sen", nameBn: "আরতি সেন", rating: 5, textEn: "Ordered a 2-tier wedding cake. Mind blowing taste and decoration! Everyone at the party asked about it. Reasonable price too.", textBn: "একটি ২-টায়ার ওয়েডিং কেক অর্ডার দিয়েছিলাম। অসাধারণ স্বাদ এবং ডেকোরেশন! যুক্তিসঙ্গত দাম।", source: "google", timeEn: "2 months ago", timeBn: "২ মাস আগে", badgeEn: "Local Guide • 8 reviews", badgeBn: "Local Guide • 8 reviews" },
  { nameEn: "Priya Sharma", nameBn: "প্রিয়া শর্মা", rating: 5, textEn: "Always my go-to place for customized fondant cakes! The detailing is mind-blowing. Service is top notch. Thank you Musu!", textBn: "কাস্টমাইজড ফন্ড্যান্ট কেকের জন্য এটি সবসময় আমার প্রথম পছন্দ! সার্ভিস অসাধারণ। ধন্যবাদ মুসু!", source: "google", timeEn: "3 months ago", timeBn: "৩ মাস আগে", badgeEn: "Local Guide • 12 reviews", badgeBn: "Local Guide • 12 reviews" },
  { nameEn: "Monalisa Ghosh", nameBn: "মোনালিসা ঘোষ", rating: 5, textEn: "Ordered a customized dream cake for my brother's graduation. It was so soft, moist and tasty! Mind blowing design and pricing.", textBn: "আমার ভাইয়ের গ্র্যাজুয়েশনের জন্য একটি কাস্টমাইজড ড্রিম কেক অর্ডার করেছিলাম। খুব নরম এবং সুস্বাদু ছিল!", source: "google", timeEn: "Edited 3 weeks ago", timeBn: "৩ সপ্তাহ আগে", badgeEn: "Local Guide • 2 reviews", badgeBn: "Local Guide • 2 reviews", ownerReplyEn: "Thank you Monalisa! Always happy to bake for your family events!", ownerReplyBn: "ধন্যবাদ মোনালিসা! আপনার পরিবারের অনুষ্ঠানের জন্য কেক বানাতে পেরে আমরা আনন্দিত!" },
  { nameEn: "Ananya Das", nameBn: "অনন্যা দাস", rating: 5, textEn: "Best bakery in Rajpur Sonarpur area! Ordered a red velvet birthday cake for my daughter and it was super soft and fresh. Everyone loved it.", textBn: "রাজপুর সোনারপুর এলাকার সেরা বেকারি! আমার মেয়ের জন্য একটি রেড ভেলভেট বার্থডে কেক অর্ডার করেছিলাম, সবাই খুব পছন্দ করেছে।", source: "google", timeEn: "1 month ago", timeBn: "১ মাস আগে", badgeEn: "Local Guide • 3 reviews", badgeBn: "Local Guide • 3 reviews" },
  { nameEn: "Tanusree Bhattacharya", nameBn: "তনুশ্রী ভট্টাচার্য", rating: 5, textEn: "Ordered a custom birthday cake for my son. Wonderful presentation, soft cake texture & top notch taste!", textBn: "আমার ছেলের জন্য একটি কাস্টম বার্থডে কেক অর্ডার দিয়েছিলাম। দুর্দান্ত প্রেজেন্টেশন এবং স্বাদ!", source: "google", timeEn: "4 months ago", timeBn: "৪ মাস আগে", badgeEn: "Local Guide • 5 reviews", badgeBn: "Local Guide • 5 reviews" },
  { nameEn: "Amit Roy", nameBn: "অমিত রায়", rating: 5, textEn: "Amazing cakes, totally loved the dream cake design for anniversary. Quality is premium.", textBn: "অসাধারণ কেক, বার্ষিকীর জন্য ড্রিম কেকের ডিজাইন খুব পছন্দ হয়েছে। প্রিমিয়াম কোয়ালিটি।", source: "google", timeEn: "7 months ago", timeBn: "৭ মাস আগে", badgeEn: "Local Guide • 15 reviews", badgeBn: "Local Guide • 15 reviews" },
  { nameEn: "Subhobrata Mondal", nameBn: "শুভব্রত মন্ডল", rating: 5, textEn: "Agree... Highly recommended! The custom cake was absolutely delicious and beautiful. Service was amazing.", textBn: "হাইলি রেকমেন্ডেড! কাস্টম কেকটি একেবারে সুস্বাদু এবং সুন্দর ছিল। সার্ভিস অসাধারণ।", source: "google", timeEn: "2 weeks ago", timeBn: "২ সপ্তাহ আগে", badgeEn: "Local Guide • 4 reviews", badgeBn: "Local Guide • 4 reviews", ownerReplyEn: "Thank you so much! Glad you loved the custom cake 💖", ownerReplyBn: "আপনাকে অনেক ধন্যবাদ! কাস্টম কেকটি আপনার পছন্দ হয়েছে জেনে আনন্দিত 💖" },
  { nameEn: "Sayan Banerjee", nameBn: "সায়ন ব্যানার্জী", rating: 4, textEn: "Cake taste was really great and fresh. Fast service and smooth delivery. Slightly sweet for my personal taste, but great quality overall.", textBn: "কেকের স্বাদ সত্যিই দারুণ এবং ফ্রেশ ছিল। দ্রুত ডেলিভারি। সামগ্রিক মান দুর্দান্ত।", source: "google", timeEn: "5 months ago", timeBn: "৫ মাস আগে", badgeEn: "Local Guide • 6 reviews", badgeBn: "Local Guide • 6 reviews" },
  { nameEn: "Rahul Verma", nameBn: "রাহুল বর্মা", rating: 4, textEn: "Good cakes and nice customization, but price is slightly on higher side compared to standard bakeries. Quality is good though.", textBn: "ভালো কেক এবং সুন্দর কাস্টমাইজেশন, তবে দাম কিছুটা বেশি। যদিও কোয়ালিটি ভালো।", source: "google", timeEn: "6 months ago", timeBn: "৬ মাস আগে", badgeEn: "Reviewer • 2 reviews", badgeBn: "Reviewer • 2 reviews" },
  { nameEn: "Swagata Sen", nameBn: "স্বাগতা সেন", rating: 5, textEn: "I always order from Bake n' Flake. Their chocolate truffle is heavenly. Keep up the good work!", textBn: "আমি সবসময় Bake n' Flake থেকে অর্ডার করি। তাদের চকোলেট ট্রাফল অসাধারণ।", source: "google", timeEn: "8 months ago", timeBn: "৮ মাস আগে", badgeEn: "Local Guide • 10 reviews", badgeBn: "Local Guide • 10 reviews" }
];

const facebookReviews = [
  { nameEn: "Anjali Gupta", nameBn: "অঞ্জলি গুপ্তা", rating: 5, textEn: "Ordered a customized fondant cake for my daughter's birthday. It looked beautiful and tasted even better.", textBn: "আমার মেয়ের জন্মদিনের জন্য একটি কাস্টমাইজড ফন্ড্যান্ট কেক অর্ডার করেছিলাম। এটি দেখতে সুন্দর ছিল এবং খেতে আরও ভাল ছিল।", source: "facebook", timeEn: "3 weeks ago", timeBn: "৩ সপ্তাহ আগে" },
  { nameEn: "Sneha Das", nameBn: "স্নেহা দাস", rating: 5, textEn: "Very nice collection of bento cakes. Perfect for small celebrations.", textBn: "বেন্টো কেকের খুব সুন্দর কালেকশন। ছোট উদযাপনের জন্য পারফেক্ট।", source: "facebook", timeEn: "1 month ago", timeBn: "১ মাস আগে" },
  { nameEn: "Riya Chakraborty", nameBn: "রিয়া চক্রবর্তী", rating: 5, textEn: "Their Bento cakes are so cute and reasonably priced! Have recommended this page to all my friends.", textBn: "তাদের বেন্টো কেকগুলো খুব সুন্দর এবং দামও সাশ্রয়ী! আমি আমার বন্ধুদের রেকমেন্ড করেছি।", source: "facebook", timeEn: "2 months ago", timeBn: "২ মাস আগে" },
  { nameEn: "Poulami Mitra", nameBn: "পৌলমী মিত্র", rating: 5, textEn: "Just received my anniversary cake. It looks exact same as the reference picture I provided! So happy with the detailing.", textBn: "আমার বিবাহবার্ষিকীর কেকটি হাতে পেলাম। এটি হুবহু রেফারেন্স ছবির মতো দেখতে!", source: "facebook", timeEn: "2 months ago", timeBn: "২ মাস আগে" },
  { nameEn: "Debanjan Saha", nameBn: "দেবাঞ্জন সাহা", rating: 4, textEn: "Tried their jar cakes last weekend. Really loved the Red Velvet one.", textBn: "গত উইকেন্ডে তাদের জার কেক ট্রাই করেছিলাম। রেড ভেলভেটটা খুব ভালো লেগেছে।", source: "facebook", timeEn: "3 months ago", timeBn: "৩ মাস আগে" },
  { nameEn: "Priyanka Nandi", nameBn: "প্রিয়াঙ্কা নন্দী", rating: 5, textEn: "Best home baker in the city. The hygiene and packaging is commendable.", textBn: "শহরের সেরা হোম বেকার। তাদের পরিচ্ছন্নতা এবং প্যাকেজিং প্রশংসনীয়।", source: "facebook", timeEn: "4 months ago", timeBn: "৪ মাস আগে" },
  { nameEn: "Sudipta Halder", nameBn: "সুদীপ্ত হালদার", rating: 5, textEn: "Loved the pizza and brownies combo! Highly recommended for evening snacks.", textBn: "পিৎজা এবং ব্রাউনির কম্বোটি দারুণ ছিল! বিকেলের স্ন্যাকসের জন্য হাইলি রেকমেন্ডেড।", source: "facebook", timeEn: "5 months ago", timeBn: "৫ মাস আগে" },
  { nameEn: "Nandini Chatterjee", nameBn: "নন্দিনী চ্যাটার্জী", rating: 5, textEn: "I was looking for a theme cake for my kid's first birthday and they delivered the perfect jungle theme cake.", textBn: "আমার বাচ্চার জন্মদিনের জন্য জঙ্গল থিম কেক খুঁজছিলাম এবং তারা ঠিক সেটাই বানিয়ে দিয়েছে।", source: "facebook", timeEn: "6 months ago", timeBn: "৬ মাস আগে" },
  { nameEn: "Sayantani Bose", nameBn: "সায়ন্তনী বসু", rating: 5, textEn: "Amazing taste and totally worth the money.", textBn: "অসাধারণ স্বাদ এবং পয়সা উসুল।", source: "facebook", timeEn: "7 months ago", timeBn: "৭ মাস আগে" },
  { nameEn: "Koushik Ghosh", nameBn: "কৌশিক ঘোষ", rating: 4, textEn: "Good behavior and fast response. Cake was also very good.", textBn: "ভালো ব্যবহার এবং দ্রুত রেসপন্স। কেকটিও খুব ভালো ছিল।", source: "facebook", timeEn: "8 months ago", timeBn: "৮ মাস আগে" }
];

const webReviews = [
  { nameEn: "Rakesh Singh", nameBn: "রাকেশ সিং", rating: 5, textEn: "The chocolate truffle is out of this world. Highly recommend Bake n' Flake!", textBn: "চকোলেট ট্রাফল অসাধারণ। বেক এন ফ্লেক হাইলি রেকমেন্ড করছি!", source: "web", timeEn: "2 days ago", timeBn: "২ দিন আগে" },
  { nameEn: "Sarmistha Paul", nameBn: "শর্মিষ্ঠা পাল", rating: 5, textEn: "Beautiful website and very easy to order. The cake got delivered right on time.", textBn: "সুন্দর ওয়েবসাইট এবং অর্ডার করা খুব সহজ। ঠিক সময়ে কেক ডেলিভারি পেয়েছি।", source: "web", timeEn: "1 week ago", timeBn: "১ সপ্তাহ আগে" },
  { nameEn: "Sourav Ganguly", nameBn: "সৌরভ গাঙ্গুলী", rating: 4, textEn: "Really appreciate the quick checkout process. The cake quality was very good.", textBn: "দ্রুত চেকআউট প্রসেসটি খুব ভালো লেগেছে। কেকের কোয়ালিটিও খুব ভালো ছিল।", source: "web", timeEn: "2 weeks ago", timeBn: "২ সপ্তাহ আগে" },
  { nameEn: "Aditi Roy", nameBn: "অদিতি রায়", rating: 5, textEn: "I ordered a butterscotch cake for my mom's birthday through the website. Flawless experience.", textBn: "ওয়েবসাইটের মাধ্যমে মায়ের জন্মদিনের জন্য বাটারস্কচ কেক অর্ডার করেছিলাম। খুব ভালো অভিজ্ঞতা।", source: "web", timeEn: "3 weeks ago", timeBn: "৩ সপ্তাহ আগে" },
  { nameEn: "Karan Johar", nameBn: "করণ জোহর", rating: 5, textEn: "Fabulous cakes! Will definitely order again.", textBn: "অসাধারণ কেক! অবশ্যই আবার অর্ডার করব।", source: "web", timeEn: "1 month ago", timeBn: "১ মাস আগে" },
  { nameEn: "Neha Sharma", nameBn: "নেহা শর্মা", rating: 5, textEn: "The dream cake was literally a dream! So soft and chocolaty.", textBn: "ড্রিম কেকটি সত্যিই অসাধারণ ছিল! খুব নরম এবং চকোলেটি।", source: "web", timeEn: "1 month ago", timeBn: "১ মাস আগে" },
  { nameEn: "Rohit Das", nameBn: "রোহিত দাস", rating: 4, textEn: "Good options available. Price is also reasonable.", textBn: "অনেক অপশন আছে। দামও সাশ্রয়ী।", source: "web", timeEn: "2 months ago", timeBn: "২ মাস আগে" },
  { nameEn: "Pallavi Dey", nameBn: "পল্লবী দে", rating: 5, textEn: "Thanks for the amazing service. Highly satisfied.", textBn: "অসাধারণ সার্ভিসের জন্য ধন্যবাদ। খুব সন্তুষ্ট।", source: "web", timeEn: "3 months ago", timeBn: "৩ মাস আগে" },
  { nameEn: "Bikash Ranjan", nameBn: "বিকাশ রঞ্জন", rating: 5, textEn: "Ordered some jar cakes and they were packed securely.", textBn: "কিছু জার কেক অর্ডার করেছিলাম, প্যাকিং খুব ভালো ছিল।", source: "web", timeEn: "4 months ago", timeBn: "৪ মাস আগে" },
  { nameEn: "Sima Dutta", nameBn: "সীমা দত্ত", rating: 5, textEn: "My kids loved the cupcakes. Very cute designs.", textBn: "আমার বাচ্চারা কাপকেকগুলো খুব পছন্দ করেছে। খুব সুন্দর ডিজাইন।", source: "web", timeEn: "5 months ago", timeBn: "৫ মাস আগে" }
];

let content = fs.readFileSync('src/constants/data.ts', 'utf8');

// replace the arrays
content = content.replace(/export const googleReviewsData: Review\[\] = \[[\s\S]*?\];/g, `export const googleReviewsData: Review[] = ${JSON.stringify(googleReviews, null, 2)};`);
content = content.replace(/export const facebookReviewsData: Review\[\] = \[[\s\S]*?\];/g, `export const facebookReviewsData: Review[] = ${JSON.stringify(facebookReviews, null, 2)};`);
content = content.replace(/export const webReviewsData: Review\[\] = \[[\s\S]*?\];/g, `export const webReviewsData: Review[] = ${JSON.stringify(webReviews, null, 2)};`);

fs.writeFileSync('src/constants/data.ts', content);
