import { Product, Review } from '../types';

export const flavours: Product[] = [
  { nameEn: "Chocolate Cakes", nameBn: "চকোলেট কেক", img: "https://i.ibb.co/xSTgDb8d/Chocolate-Cakes-1.png" },
  { nameEn: "Butterscotch Cakes", nameBn: "বাটারস্কচ কেক", img: "https://i.ibb.co/fYcwMKdc/Butterscotch-Cakes-1.png" },
  { nameEn: "Vanilla Cakes", nameBn: "ভ্যানিলা কেক", img: "https://i.ibb.co/qMBQG6Nk/Vanilla-Cake-1.png" },
  { nameEn: "Chocolate Truffle", nameBn: "চকোলেট ট্রাফল", img: "https://i.ibb.co/MKF765x/Chocolate-Truffle-Cakes-1.png" },
  { nameEn: "Pineapple Cakes", nameBn: "পাইনঅ্যাপল কেক", img: "https://i.ibb.co/gbC67jD7/PIneapple-Cake-1.png" },
  { nameEn: "Mango Cakes", nameBn: "ম্যাংগো কেক", img: "https://i.ibb.co/q3M2pvxs/Mango-Cake-1.png" },
  { nameEn: "Strawberry Cakes", nameBn: "স্ট্রবেরি কেক", img: "https://i.ibb.co/7JYt6dJp/Strawberry-Cakes-1.jpg" },
  { nameEn: "Red Velvet Cakes", nameBn: "রেড ভেলভেট কেক", img: "https://i.ibb.co/s9gGgtpk/Red-velvet-1.png" },
  { nameEn: "Fresh Fruit Cake", nameBn: "ফ্রেশ ফ্রুট Cake", img: "https://i.ibb.co/F4V5yd16/Fresh-Fruit-Cake-1.png" },
  { nameEn: "Forest Range", nameBn: "ফরেস্ট রেঞ্জ", img: "https://i.ibb.co/q3P990gk/Black-Forest-1.png" },
  { nameEn: "Oreo Cakes", nameBn: "ওরিও কেক", img: "https://i.ibb.co/nprbQJC/Oreo-Cake-2.png" },
  { nameEn: "Alcohol base Cake", nameBn: "অ্যালকোহল বেস Cake", img: "https://i.ibb.co/xSj9RRdz/Alcohol-Cake-01.png" },
  { nameEn: "Coffee Mocha", nameBn: "কফি মোকা", img: "https://i.ibb.co/4w2jyMmB/Coffee-Cake-1.png" },
  { nameEn: "Rasmalai Cake", nameBn: "রসমলাই Cake", img: "https://i.ibb.co/4RBygSqR/Rasmalai-Cake-1.png" },
  { nameEn: "Orange Cake", nameBn: "অরেঞ্জ কেক", img: "https://i.ibb.co/RTSFv7dG/Orrange-Cake-1.png" },
  { nameEn: "KitKat Cakes", nameBn: "কিটক্যাট কেক", img: "https://i.ibb.co/k26bhF2H/Kitkat-1.png" }
];

export const gifts: Product[] = [
  { nameEn: "Birthday Cakes", nameBn: "জন্মদিনের কেক", img: "https://i.ibb.co/hJyMC4CY/Birthday-Cake-1.jpg" },
  { nameEn: "Anniversary Cakes", nameBn: "অ্যানিভার্সারি কেক", img: "https://i.ibb.co/5gDy06k7/Aniversary-Cake-2.png" },
  { nameEn: "Teacher's Day", nameBn: "টিচার্স ডে", img: "https://i.ibb.co/fzVDfmhj/FRESH-FLOWER-CAKE-1.jpg" },
  { nameEn: "Customised Chocolates", nameBn: "কাস্টমাইজড চকোলেট", img: "https://i.ibb.co/Rp8C27Xt/Customized-Chocolates-2.jpg" },
  { nameEn: "Father's Day Cake", nameBn: "ফাদার্স ডে কেক", img: "https://i.ibb.co/YT2LRm2x/Father-s-Day-Cake-1.png" },
  { nameEn: "Mother's Day Cake", nameBn: "মাদার্স ডে কেক", img: "https://i.ibb.co/4n26zZCq/2.jpg" },
  { nameEn: "Christmas Cake", nameBn: "ক্রিসমাস কেক", img: "https://i.ibb.co/7NKqnNsd/Christmas-Cake-4.png" },
  { nameEn: "Baby Shower Cake", nameBn: "বেবি শাওয়ার কেক", img: "https://i.ibb.co/RTTYsqVd/KIDS-CAKE.png" },
  { nameEn: "Rice Ceremony cakes", nameBn: "অন্নপ্রাশনের কেক", img: "https://i.pinimg.com/736x/6c/bb/7f/6cbb7f551f96722c5b6f01141b5b4aa6.jpg" }
];

export const moreOptionsData: Product[] = [
  { nameEn: "Fresh Flower Cake", nameBn: "ফ্রেশ ফ্লাওয়ার কেক", img: "https://i.ibb.co/fzVDfmhj/FRESH-FLOWER-CAKE-1.jpg", rounded: true },
  { nameEn: "Doll Cakes", nameBn: "ডল কেক", img: "https://i.ibb.co/bGXr5qW/DOLL-CAKE-1.png", rounded: true },
  { nameEn: "Half Cakes", nameBn: "হাফ কেক", img: "https://i.ibb.co/V0yhspQm/HALF-CAKE-1.jpg", rounded: true },
  { nameEn: "Tier Cakes", nameBn: "টিয়ার কেক", img: "https://i.ibb.co/Xx1SBWb6/TIRE-CAKE.png", rounded: true },
  { nameEn: "Number Cakes", nameBn: "নম্বর কেক", img: "https://i.ibb.co/20VxsJxG/Number-Cake.jpg", rounded: true },
  { nameEn: "Kids Cakes", nameBn: "বাচ্চাদের কেক", img: "https://i.ibb.co/xrgZZcx/Kids-Cake-1.png", rounded: true },
  { nameEn: "Fondant and Semi Fondant Cakes", nameBn: "ফন্ডেন্ট ও সেমি ফন্ডেন্ট কেক", img: "https://i.ibb.co/ZpB76tN5/FONDANT-1.png", rounded: true },
  { nameEn: "Glitter Cake", nameBn: "গ্লিটার কেক", img: "https://i.ibb.co/xt8VVwmW/Gliter-Cake-1.jpg", rounded: true },
  { nameEn: "Customize Theme Cake", nameBn: "কাস্টমাইজড থিম কেক", img: "https://i.ibb.co/9mnwZgX4/TIRE-CAKE1.png", rounded: true },
  { nameEn: "Cheesecakes", nameBn: "চিজকেকস", img: "https://i.pinimg.com/736x/bc/b6/0c/bcb60c22cedf8400a2e2c6b0679c22e5.jpg", rounded: true },
  { nameEn: "Photo Cakes", nameBn: "ফটো কেক", img: "https://i.ibb.co/rR23zjJp/Photo-Cake-1.png", rounded: true },
  { nameEn: "Bento Cakes", nameBn: "বেন্টো কেক", img: "https://i.ibb.co/3yDW6YkY/BENTO-1.jpg", rounded: true },
  { nameEn: "Mousse", nameBn: "মাউস", img: "https://i.ibb.co/xt88WGMM/Mousse-1.jpg", rounded: true },
  { nameEn: "Jar and Glass Cakes", nameBn: "জার এবং গ্লাস কেক", img: "https://i.ibb.co/9HDRRk0F/Jur-cake.png", rounded: true },
  { nameEn: "Pinata Cakes", nameBn: "পিনাটা কেক", img: "https://i.ibb.co/gbqnmvzd/02.jpg", rounded: true },
  { nameEn: "Cupcakes and Muffins", nameBn: "কাপকেক ও মাফিন", img: "https://i.ibb.co/jkNm1Zq8/Cupcakes-1.jpg", rounded: true },
  { nameEn: "Pizza & Patties", nameBn: "পিজ্জা ও প্যাটিস", img: "https://i.ibb.co/sTLSSsj/PIZZA-BUNS-1.png", rounded: true },
  { nameEn: "Brownies", nameBn: "ব্রাউনিজ", img: "https://i.ibb.co/F4rgH3Wn/Brownies-1.jpg", rounded: true }
];

export const googleReviewsData: Review[] = [
  { 
    nameEn: "Subhobrata Mondal", 
    nameBn: "শুভব্রত মন্ডল", 
    timeEn: "2 weeks ago", 
    timeBn: "২ সপ্তাহ আগে", 
    rating: 5, 
    date: new Date('2026-07-13'), 
    textEn: "Agree... Highly recommended! The custom cake was absolutely delicious and beautiful. Service was amazing.", 
    textBn: "একদম একমত... উচ্চ প্রস্তাবিত! কাস্টম কেকটি একেবারে সুস্বাদু এবং সুন্দর ছিল। পরিষেবা আশ্চর্যজনক ছিল।", 
    avatar: "https://ui-avatars.com/api/?name=Subhobrata+Mondal&background=f472b6&color=fff",
    badgeEn: "Local Guide • 4 reviews • 10 photos",
    badgeBn: "লোকাল গাইড • ৪ রিভিউ • ১০ ছবি",
    ownerReplyEn: "Thank you so much! Glad you loved the custom cake ❤️",
    ownerReplyBn: "আপনাকে অনেক ধন্যবাদ! কাস্টম কেকটি আপনার ভালো লেগেছে জেনে আনন্দিত ❤️",
    topics: ["custom cakes", "service", "soft cake"],
    likes: 1
  },
  { 
    nameEn: "Monalisa Ghosh", 
    nameBn: "মোনালিসা ঘোষ", 
    timeEn: "Edited 3 weeks ago", 
    timeBn: "সম্পাদিত ৩ সপ্তাহ আগে", 
    rating: 5, 
    date: new Date('2026-07-06'), 
    textEn: "Ordered a customized dream cake for my brother's graduation. It was so soft, moist and tasty! Mind blowing design and pricing.", 
    textBn: "ভাইয়ের গ্র্যাজুয়েশনের জন্য কাস্টমাইজড ড্রিম কেক অর্ডার করেছিলাম। এটা খুবই নরম, ময়শ্চারাইজড ও সুস্বাদু ছিল! অসাধারণ ডিজাইন এবং দাম।", 
    avatar: "https://ui-avatars.com/api/?name=Monalisa+Ghosh&background=06b6d4&color=fff",
    badgeEn: "Local Guide • 2 reviews • 11 photos",
    badgeBn: "লোকাল গাইড • ২ রিভিউ • ১১ ছবি",
    ownerReplyEn: "Thank you Monalisa! Always happy to bake for your family events!",
    ownerReplyBn: "ধন্যবাদ মোনালিসা! আপনার পারিবারিক অনুষ্ঠানে কেক বানাতে পেরে আমরা আনন্দিত!",
    topics: ["custom cakes", "dream cake", "soft cake", "price"],
    likes: 3
  },
  { 
    nameEn: "Ananya Das", 
    nameBn: "অনন্যা দাস", 
    timeEn: "1 month ago", 
    timeBn: "১ মাস আগে", 
    rating: 5, 
    date: new Date('2026-06-20'), 
    textEn: "Best bakery in Rajpur Sonarpur area! Ordered a red velvet birthday cake for my daughter and it was super soft and fresh. Everyone loved it.", 
    textBn: "রাজপুর সোনারপুর এলাকার সেরা বেকারি! আমার মেয়ের জন্মদিনের জন্য একটি রেড ভেলভেট কেক অর্ডার করেছিলাম এবং এটি খুব নরম এবং তাজা ছিল। সবাই এটি পছন্দ করেছে।", 
    avatar: "https://ui-avatars.com/api/?name=Ananya+Das&background=db2777&color=fff",
    badgeEn: "Local Guide • 3 reviews",
    badgeBn: "লোকাল গাইড • ৩ রিভিউ",
    topics: ["birthday cake", "soft cake", "service"],
    likes: 2
  },
  { 
    nameEn: "Aarti Sen", 
    nameBn: "আরতি সেন", 
    timeEn: "2 months ago", 
    timeBn: "২ মাস আগে", 
    rating: 5, 
    date: new Date('2026-05-15'), 
    textEn: "Ordered a 2-tier wedding cake. Mind blowing taste and decoration! Everyone at the party asked about it. Reasonable price too.", 
    textBn: "২ টিয়ারের একটি ওয়েডিং কেক অর্ডার করেছিলাম। অসাধারণ স্বাদ এবং ডেকোরেশন! পার্টির সবাই কেকটার ব্যাপারে জিজ্ঞেস করছিল। দামও মানানসই।", 
    avatar: "https://ui-avatars.com/api/?name=Aarti+Sen&background=fb7185&color=fff",
    badgeEn: "Local Guide • 8 reviews",
    badgeBn: "লোকাল গাইড • ৮ রিভিউ",
    topics: ["custom cakes", "price"],
    likes: 5
  },
  { 
    nameEn: "Priya Sharma", 
    nameBn: "প্রিয়া শর্মা", 
    timeEn: "3 months ago", 
    timeBn: "৩ মাস আগে", 
    rating: 5, 
    date: new Date('2026-04-10'), 
    textEn: "Always my go-to place for customized fondant cakes! The detailing is mind-blowing. Service is top notch. Thank you Musu!", 
    textBn: "কাস্টমাইজড ফন্ডেন্ট কেকের জন্য সর্বদা আমার প্রিয় জায়গা! ডিটেইলিং মন ছুঁয়ে যাওয়ার মতো। সার্ভিস দারুণ। মুসুকে ধন্যবাদ!", 
    avatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=be185d&color=fff",
    badgeEn: "Local Guide • 12 reviews",
    badgeBn: "লোকাল গাইড • ১২ রিভিউ",
    topics: ["custom cakes", "service"],
    likes: 4
  },
  { 
    nameEn: "Tanusree Bhattacharya", 
    nameBn: "তনুশ্রী ভট্টাচার্য", 
    timeEn: "4 months ago", 
    timeBn: "৪ মাস আগে", 
    rating: 5, 
    date: new Date('2026-03-01'), 
    textEn: "Ordered a custom birthday cake for my son. Wonderful presentation, soft cake texture & top notch taste!", 
    textBn: "আমার ছেলের জন্য কাস্টম বার্থডে কেক অর্ডার করেছিলাম। দারুণ পরিবেশনা, নরম টেক্সচার এবং চমৎকার স্বাদ!", 
    avatar: "https://ui-avatars.com/api/?name=Tanusree+Bhattacharya&background=8b5cf6&color=fff",
    badgeEn: "Local Guide • 5 reviews",
    badgeBn: "লোকাল গাইড • ৫ রিভিউ",
    topics: ["birthday cake", "soft cake", "custom cakes"],
    likes: 2
  },
  { 
    nameEn: "Sayan Banerjee", 
    nameBn: "সায়ন ব্যানার্জী", 
    timeEn: "5 months ago", 
    timeBn: "৫ মাস আগে", 
    rating: 4, 
    date: new Date('2026-02-14'), 
    textEn: "Cake taste was really great and fresh. Fast service and smooth delivery. Slightly sweet for my personal taste, but great quality overall.", 
    textBn: "কেকের স্বাদ আসলেই ভালো এবং টাটকা ছিল। দ্রুত সার্ভিস ও স্মুথ ডেলিভারি। আমার মিষ্টি একটু বেশি লেগেছে তবে সামগ্রিকভাবে ভালো কোয়ালিটি।", 
    avatar: "https://ui-avatars.com/api/?name=Sayan+Banerjee&background=3b82f6&color=fff",
    badgeEn: "Local Guide • 6 reviews",
    badgeBn: "লোকাল গাইড • ৬ রিভিউ",
    topics: ["service", "price"],
    likes: 1
  },
  { 
    nameEn: "Rahul Verma", 
    nameBn: "রাহুল ভার্মা", 
    timeEn: "6 months ago", 
    timeBn: "৬ মাস আগে", 
    rating: 3, 
    date: new Date('2026-01-20'), 
    textEn: "Good cakes and nice customization, but price is slightly on higher side compared to standard bakeries. Quality is good though.", 
    textBn: "কেক ভালো এবং কাস্টমাইজেশনও সুন্দর, কিন্তু সাধারণ বেকারির তুলনায় দামটা একটু বেশি। তবে মান ভালো।", 
    avatar: "https://ui-avatars.com/api/?name=Rahul+Verma&background=64748b&color=fff",
    badgeEn: "Reviewer • 2 reviews",
    badgeBn: "রিভিউয়ার • ২ রিভিউ",
    topics: ["price", "custom cakes"],
    likes: 0
  },
  { 
    nameEn: "Amit Roy", 
    nameBn: "অমিত রায়", 
    timeEn: "7 months ago", 
    timeBn: "৭ মাস আগে", 
    rating: 5, 
    date: new Date('2025-12-10'), 
    textEn: "Amazing cakes, totally loved the dream cake design for anniversary. Quality is premium.", 
    textBn: "অসাধারণ কেক, বার্ষিকী কেকের ডিজাইন খুব পছন্দ হয়েছে। কোয়ালিটি প্রিমিয়াম।", 
    avatar: "https://ui-avatars.com/api/?name=Amit+Roy&background=10b981&color=fff",
    badgeEn: "Local Guide • 15 reviews",
    badgeBn: "লোকাল গাইড • ১৫ রিভিউ",
    topics: ["dream cake", "custom cakes"],
    likes: 2
  }
];

export const facebookReviewsData: Review[] = [
  { 
    nameEn: "Priya Sharma", 
    nameBn: "প্রিয়া শর্মা", 
    timeEn: "1 week ago", 
    timeBn: "১ সপ্তাহ আগে", 
    rating: 5, 
    date: new Date('2026-07-20'), 
    textEn: "Always my go-to place for customized fondant cakes! The detailing is mind-blowing. Thank you Musu!", 
    textBn: "কাস্টমাইজড ফন্ডেন্ট কেকের জন্য সর্বদা আমার প্রিয় জায়গা! বিবরণগুলি মন ছুঁয়ে যাওয়ার মতো। মুসুকে ধন্যবাদ!", 
    avatar: "https://ui-avatars.com/api/?name=Priya+Sharma&background=be185d&color=fff", 
    recommends: true,
    badgeEn: "Recommends Bake n' Flake",
    badgeBn: "বেক অ্যান্ড ফ্লেক রেকমেন্ড করেছেন",
    topics: ["custom cakes", "service"]
  },
  { 
    nameEn: "Kabir Khan", 
    nameBn: "কবির খান", 
    timeEn: "2 weeks ago", 
    timeBn: "২ সপ্তাহ আগে", 
    rating: 5, 
    date: new Date('2026-07-12'), 
    textEn: "I regularly order birthday cakes from Bake n Flake. Never disappointed. Always premium quality & prompt service.", 
    textBn: "আমি নিয়মিত বেক অ্যান্ড ফ্লেক থেকে বার্থডে কেক অর্ডার করি। কখনো হতাশ হইনি। সবসময় প্রিমিয়াম কোয়ালিটি এবং দ্রুত সার্ভিস পেয়েছি।", 
    avatar: "https://ui-avatars.com/api/?name=Kabir+Khan&background=e11d48&color=fff", 
    recommends: true,
    badgeEn: "Recommends Bake n' Flake",
    badgeBn: "বেক অ্যান্ড ফ্লেক রেকমেন্ড করেছেন",
    topics: ["birthday cake", "service"]
  },
  { 
    nameEn: "Rohan Roy", 
    nameBn: "রোহন রায়", 
    timeEn: "1 month ago", 
    timeBn: "১ মাস আগে", 
    rating: 4, 
    date: new Date('2026-06-18'), 
    textEn: "The cake design was beautiful and exact. Price was fair and delivery on time.", 
    textBn: "কেকের ডিজাইন সুন্দর এবং নির্ভুল ছিল। দাম ন্যায্য ছিল এবং সঠিক সময়ে পৌঁছায়।", 
    avatar: "https://ui-avatars.com/api/?name=Rohan+Roy&background=94a3b8&color=fff", 
    recommends: true,
    badgeEn: "Recommends Bake n' Flake",
    badgeBn: "বেক অ্যান্ড ফ্লেক রেকমেন্ড করেছেন",
    topics: ["price", "custom cakes"]
  },
  { 
    nameEn: "Megha Gupta", 
    nameBn: "মেঘা গুপ্ত", 
    timeEn: "2 months ago", 
    timeBn: "২ মাস আগে", 
    rating: 5, 
    date: new Date('2026-05-20'), 
    textEn: "Loved the anniversary dream cake! Musu is very cooperative and friendly.", 
    textBn: "অ্যানিভার্সারি ড্রিম কেকটা খুব পছন্দ হয়েছে! মুসু খুব সহযোগিতামূলক ও বন্ধুত্বপূর্ণ।", 
    avatar: "https://ui-avatars.com/api/?name=Megha+Gupta&background=ec4899&color=fff", 
    recommends: true,
    badgeEn: "Recommends Bake n' Flake",
    badgeBn: "বেক অ্যান্ড ফ্লেক রেকমেন্ড করেছেন",
    topics: ["dream cake", "service"]
  }
];
